### ISSUE TITLE
Changing Configkeys to use dictionary in other language

### ISSUE THREAD

**Issue by riannek** [WojciechMula/aspell-python#7]
Hi, 
I've got a question, I'm trying to use aspell-python with a Dutch dictionary and wordlist. How can I set the Configkeys 'data-dir' and 'dict-dir' to point to my directories?
I've tried to use something like this: 
aspell.ConfigKeys()[5] = 'C:/TmpInstall/data/'
aspell.ConfigKeys()[7] = 'C:/TmpInstall/dict/'
But I can't find the right syntax. 

Regards, 
Rianne

**Comment by WojciechMula** [comment]
You have to pass the options via constructor, as described in section "Classes" (https://github.com/WojciechMula/aspell-python#classes).

Changing a configuration of existing speller is not yet supported, there is issue #5 for this feature.

**Comment by riannek** [comment]
Hi,
Thanks for the pointer. I can set the dictionary files now, but got a follow-up question immediately.I'm getting this error: 
Traceback (most recent call last):
  File "//tsn.tno.nl/Data/Projects/060/0/08675/Werkdocumenten/Sentiment Analysis/Code/Spellchecker.py", line 22, in <module>
    check(term, language)
  File "//tsn.tno.nl/Data/Projects/060/0/08675/Werkdocumenten/Sentiment Analysis/Code/Spellchecker.py", line 14, in check
    s = aspell.Speller(('lang', language),('dict-dir','/Home/Desktops/TmpInstall/dict'), ('data-dir','/Home/Desktops/TmpInstall/data'))
aspell.AspellSpellerError: The file "Home/Desktops/TmpInstall/dict/nl.rws" is not in the proper format.

 I'm working under Windows and I tried to install the dictionary files using the binaries given at http://aspell.net/win32/ , but apparently it doesn't work like that. Is it possible this way to install dictionaries in other languages, or should it be done completely different?

Thanks, 

Rianne

**Comment by WojciechMula** [comment]
Rianne, regarding windows problems check the commit 063d028f602797f9b12fd260702107897594194b, the contributed text by Eric might help you.
